### ISSUE TITLE
UI: Search sometimes return 0 results

### ISSUE THREAD

**Issue by okybaca** [yacy/yacy_search_server#499]
Search sometimes return 0 results, eventhough there are results in a local index. After repeating search, results are shown. 
This is confusing for the search users and a is a big stopper in YaCy usage. Noone will click on the search button again after seeing 0 results and therefore think yacy didn't find anything. 
If this issue is not easily fixable, it should at least show message like "you can try to click 'search' once more, maybe some results will appear."

**Comment by voarsh2** [comment]
Same here.

**Comment by yacylover** [comment]
Just browse to http://localhost:8090/ConfigPortal_p.html and set Remote results resorting to Automated, with JavaScript in the browser. Then press button 'Change search page' and you're all set.

**Comment by Orbiter** [comment]
I can confirm the problem. I would probably also consider the option of @yacylover as a permanent setting, but not as only fix but as additional setting to an actual fix.

**Comment by Orbiter** [comment]
maybe I found the bug, but I am not completely sure. The function processItem in yacysort.js had to get a html page, not a json object. This may or may not have caused the problem, but it could also be connected with a problem of the search result cache server-side. I also fixed that problem too: cacheable search results had been 0-hit results, that is now not any more the case. The problem would have appeared in case that at the time where the result is shown, not one result has appeared, even if more would come later. 
Finally, I also switched the switch on that @yacylover suggested. I believe the result is now not so bad.
To be pretty sure about the problem also more log lines had been added when 0 results appear to make it easier to continue with this bug here if it appears again. For now, I want to close this.

**Comment by Orbiter** [comment]
I added another commit for this issue: https://github.com/yacy/yacy_search_server/commit/49f445d556ee98c494760e08d44b40455e392a13

**Comment by okybaca** [comment]
Great, @orbiter, I tested and it seems that it fixed the issue! At least in
most cases. 

(Sometimes, it still happens, that the result counts and next page buttons
are shown, but no results actually listed.  After refresh, they appear. 
Don't know if related.)

Thanks for fixing these 'core' functions, which make YaCy more day-to-day
useful, amid focusing on all these thrilling new AI features!
